services:
  - type: web
    name: translator-app
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y portaudio19-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicornÂ app:app